const swaggerAutogen = require("swagger-autogen")();
const doc = {
  info: {
    version: "1.0.0",
    title: "Techhype-API",
    description:
      "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  host: process.env.BASE_URL,
  securityDefinitions: {
    // Define your security definitions here
    JWT: {
      type: "apiKey",
      name: "Authorization",
      in: "header",
    },
  },
  security: [{ JWT: [] }], // Apply JWT security to all routes
  definitions: {
    UserLogin: {
      $email: "glenn@techhype.no",
      $password: "Password938#",
    },
    UserSignup: {
      $firstName: "Glenn",
      $lastName: "Larsen",
      $email: "glenn@techhype.no",
      $password: "Password938#",
    },
    Card: {
      $name: "Work Card",
    },
    CardProfile: {
      $name: "My Profile",
      $title: "Mr",
      $firstName: "Glenn",
      $lastName: "Larsen",
      $birthday: "06.12.1990",
      $phone: "91771028",
      $email: "glenn@techhype.no",
      $website: "www.techhype.no",
      $website2: "www.hjemferd.no",
    },
    FileUpload: {
      type: "object",
      properties: {
        image: {
          type: "file",
          description: "Image to upload (e.g., JPEG, PNG)",
        },
      },
      required: ["image"], // Define required fields
    },
    Address: {
      $country: "Norway",
      $street: "Vestre Holbergsallmenningen 15",
      $postalCode: "3002",
      $state: "Vestland",
      $city: "Bergen",
    },
    SocialMedia: {
      $facebookLink: "www.facebook.com/Erik",
      $linkedinLink: "www.linkedIn.com",
      $snapLink: "www.snapchat.com",
      $instagramLink: "www.instagram.com/akam",
    },
    WorkInfo: {
      $company: "Techhype AS",
      $position: "CEO",
      $workPhone: "9177128",
      $workEmail: "glenn@techhype.no",
    },
  },
};

const outputFile = "./swagger-output.json";
const endpointsFiles = ["./app.js"];

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
  require("./bin/www");
});
